// Persistent server over Vcoproc_axi_sim_top exposing ONLY driver-visible primitives: MMIO
// register load/store on the dmem port, and a host-memory backdoor into u_ram_rd/u_ram_wr
// (standing in for what a real AXI-attached DRAM would hold). No knowledge of the tiling
// scheduler or matmul semantics lives here -- see sched/coproc_backend.py for that.
//
// Line protocol on stdin/stdout, loops until EOF:
//   REGW <addr_hex> <val_hex>   -- SD store (dmem_funct3=3'b011), one clock
//   REGR <addr_hex>             -- LD, prints "<val_hex>"
//   MEMW <RD|WR> <byte_addr> <n_bytes> <hex bytes, no spaces>  -- backdoor write into u_ram_rd/u_ram_wr
//   MEMR <RD|WR> <byte_addr> <n_bytes>                          -- prints hex bytes read back
//   TICK <n>                    -- advance n clocks
//   IRQ                         -- prints "<0|1>"
//   CYC                         -- prints total clocks elapsed since reset
//   BEATS                       -- prints "<rd_beat_count> <wr_beat_count>" AXI beat totals
//   STALL <rd_mask_hex> <wr_mask_hex> -- sets rd/wr_stall_mask (seeds fixed at construction)
#include <cstdio>
#include <cstdint>
#include <cstring>
#include <vector>
#include "Vcoproc_axi_sim_top.h"
#include "Vcoproc_axi_sim_top_coproc_axi_sim_top.h"
#include "ram_types.h" // generated by the Makefile: defines RdRamT/WrRamT (see comment there)
#include "verilated.h"

static uint64_t g_cyc = 0;

static void tick(Vcoproc_axi_sim_top* top) {
    top->clk = 0; top->eval();
    top->clk = 1; top->eval();
    g_cyc++;
}

static void regw(Vcoproc_axi_sim_top* top, uint64_t addr, uint64_t val) {
    top->dmem_addr = addr; top->dmem_wdata = val; top->dmem_wen = 1; top->dmem_funct3 = 0b011;
    tick(top);
    top->dmem_wen = 0;
}

static uint64_t regr(Vcoproc_axi_sim_top* top, uint64_t addr) {
    top->dmem_addr = addr; top->dmem_wen = 0; top->dmem_funct3 = 0b011;
    top->eval();
    return top->dmem_rdata;
}

// hex string of exactly 2*n characters -> n bytes (little bit fiddly but n_bytes is always small here)
static void hex_to_bytes(const char* hex, uint8_t* out, int n) {
    for (int i = 0; i < n; i++) {
        unsigned v;
        sscanf(hex + 2 * i, "%2x", &v);
        out[i] = (uint8_t)v;
    }
}

static void bytes_to_hex(const uint8_t* in, int n, char* out) {
    for (int i = 0; i < n; i++) sprintf(out + 2 * i, "%02x", in[i]);
    out[2 * n] = '\0';
}

template <typename RamT>
static void mem_write(RamT* ram, int wbytes, uint32_t byte_addr, int n_bytes, const uint8_t* data) {
    uint32_t word = byte_addr / wbytes;
    int off = byte_addr % wbytes;
    int done = 0;
    while (done < n_bytes) {
        int chunk = wbytes - off;
        if (chunk > n_bytes - done) chunk = n_bytes - done;
        uint8_t* wbuf = reinterpret_cast<uint8_t*>(&ram->mem[word]);
        memcpy(wbuf + off, data + done, chunk);
        done += chunk;
        word++;
        off = 0;
    }
}

template <typename RamT>
static void mem_read(RamT* ram, int wbytes, uint32_t byte_addr, int n_bytes, uint8_t* out) {
    uint32_t word = byte_addr / wbytes;
    int off = byte_addr % wbytes;
    int done = 0;
    while (done < n_bytes) {
        int chunk = wbytes - off;
        if (chunk > n_bytes - done) chunk = n_bytes - done;
        const uint8_t* rbuf = reinterpret_cast<const uint8_t*>(&ram->mem[word]);
        memcpy(out + done, rbuf + off, chunk);
        done += chunk;
        word++;
        off = 0;
    }
}

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    Vcoproc_axi_sim_top* top = new Vcoproc_axi_sim_top;

    top->rst = 1; top->dmem_wen = 0;
    top->rd_stall_mask = 0; top->wr_stall_mask = 0;
    top->rd_stall_seed = 0xACE1u; top->wr_stall_seed = 0xBEEFu;
    tick(top); tick(top);
    top->rst = 0;
    tick(top);
    g_cyc = 0; // count cycles from the driver's first command, not reset

    const int RD_WBYTES = sizeof(((RdRamT*)nullptr)->mem[0]);
    const int WR_WBYTES = sizeof(((WrRamT*)nullptr)->mem[0]);

    char line[1 << 20];
    while (fgets(line, sizeof(line), stdin)) {
        char cmd[16];
        if (sscanf(line, "%15s", cmd) != 1) continue;

        if (!strcmp(cmd, "REGW")) {
            uint64_t addr, val;
            sscanf(line, "REGW %llx %llx", (unsigned long long*)&addr, (unsigned long long*)&val);
            regw(top, addr, val);
            printf("OK\n");
        } else if (!strcmp(cmd, "REGR")) {
            uint64_t addr;
            sscanf(line, "REGR %llx", (unsigned long long*)&addr);
            printf("%llx\n", (unsigned long long)regr(top, addr));
        } else if (!strcmp(cmd, "MEMW")) {
            char which[4]; uint32_t addr; int n;
            char hex[1 << 19];
            sscanf(line, "MEMW %3s %x %d %s", which, &addr, &n, hex);
            std::vector<uint8_t> buf(n);
            hex_to_bytes(hex, buf.data(), n);
            if (!strcmp(which, "RD")) mem_write(top->coproc_axi_sim_top->u_ram_rd, RD_WBYTES, addr, n, buf.data());
            else mem_write(top->coproc_axi_sim_top->u_ram_wr, WR_WBYTES, addr, n, buf.data());
            printf("OK\n");
        } else if (!strcmp(cmd, "MEMR")) {
            char which[4]; uint32_t addr; int n;
            sscanf(line, "MEMR %3s %x %d", which, &addr, &n);
            std::vector<uint8_t> buf(n);
            if (!strcmp(which, "RD")) mem_read(top->coproc_axi_sim_top->u_ram_rd, RD_WBYTES, addr, n, buf.data());
            else mem_read(top->coproc_axi_sim_top->u_ram_wr, WR_WBYTES, addr, n, buf.data());
            std::vector<char> hex(2 * n + 1);
            bytes_to_hex(buf.data(), n, hex.data());
            printf("%s\n", hex.data());
        } else if (!strcmp(cmd, "TICK")) {
            int n;
            sscanf(line, "TICK %d", &n);
            for (int i = 0; i < n; i++) tick(top);
            printf("OK\n");
        } else if (!strcmp(cmd, "IRQ")) {
            printf("%d\n", (int)top->irq);
        } else if (!strcmp(cmd, "CYC")) {
            printf("%llu\n", (unsigned long long)g_cyc);
        } else if (!strcmp(cmd, "BEATS")) {
            printf("%u %u\n", top->coproc_axi_sim_top->rd_beat_count, top->coproc_axi_sim_top->wr_beat_count);
        } else if (!strcmp(cmd, "STALL")) {
            unsigned rd_mask, wr_mask;
            sscanf(line, "STALL %x %x", &rd_mask, &wr_mask);
            top->rd_stall_mask = rd_mask; top->wr_stall_mask = wr_mask;
            printf("OK\n");
        }
        fflush(stdout);
    }

    delete top;
    return 0;
}
