// Streams M activation rows through the weight-stationary NxN systolic array with the skew the
// RTL requires (row r of vector k on act_in[r] at tick k+r), and diffs psum_out against a golden
// C = A @ W read from vector files generated by model/gen_vectors.py.
//
// Latency derivation (see comment above the deskew loop for the full recurrence): for a weight
// held stationary, PE(r,c)'s registered psum after tick i is
//   P(r,c,i) = sum_{r'=0..r} act_row_{r'}(i - (r-r') - c) * w(r',c)
// Substituting the skewed feed act_row_r(k+r) = A[k][r] makes every row's contribution land on
// the same tick regardless of r: output column c of vector k is valid after tick i = k + c + N-1.
// Streaming K=M vectors therefore needs ticks i = 0 .. (M-1)+2*(N-1), i.e. M+2N-2 ticks total.

#include <cstdio>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <type_traits>
#include "Vtop.h"
#include "verilated.h"

#ifndef TB_N
#define TB_N 4
#endif
static const int N = TB_N;

// Generic byte pack/unpack over Verilator's scalar port types (CData/SData/IData/QData) and its
// wide-port type (VlWide<W>, which behaves like a uint32_t[] via operator[]/implicit conversion).
template <typename T>
static void put_byte(T& sig, int byte_idx, uint8_t v) {
    if constexpr (std::is_integral<T>::value) {
        T mask = (T)((T)0xFF << (byte_idx * 8));
        sig = (T)((sig & ~mask) | ((T)v << (byte_idx * 8)));
    } else {
        int word = byte_idx / 4, off = (byte_idx % 4) * 8;
        sig[word] = (sig[word] & ~(0xFFu << off)) | ((uint32_t)v << off);
    }
}

template <typename T>
static void zero_sig(T& sig) {
    if constexpr (std::is_integral<T>::value) sig = 0;
    else for (size_t w = 0; w < T::Words; w++) sig[w] = 0;
}

template <typename T>
static uint8_t get_byte(const T& sig, int byte_idx) {
    if constexpr (std::is_integral<T>::value) {
        return (uint8_t)((sig >> (byte_idx * 8)) & 0xFF);
    } else {
        int word = byte_idx / 4, off = (byte_idx % 4) * 8;
        return (uint8_t)((sig[word] >> off) & 0xFF);
    }
}

static void tick(Vtop* top) {
    top->clk = 0; top->eval();
    top->clk = 1; top->eval();
}

struct Case {
    std::string name;
    std::vector<std::vector<int8_t>> a;   // M x N
    std::vector<std::vector<int8_t>> w;   // N x N
    std::vector<std::vector<int32_t>> c;  // M x N (golden)
};

static bool load_case(const std::string& path, Case& out) {
    std::ifstream f(path);
    if (!f) { fprintf(stderr, "cannot open %s\n", path.c_str()); return false; }
    int n, m;
    f >> n >> m;
    if (n != N) { fprintf(stderr, "%s: N mismatch (file has %d, TB built for %d)\n", path.c_str(), n, N); return false; }
    out.a.assign(m, std::vector<int8_t>(n));
    out.w.assign(n, std::vector<int8_t>(n));
    out.c.assign(m, std::vector<int32_t>(n));
    for (int i = 0; i < m; i++)
        for (int j = 0; j < n; j++) { int v; f >> v; out.a[i][j] = (int8_t)v; }
    for (int i = 0; i < n; i++)
        for (int j = 0; j < n; j++) { int v; f >> v; out.w[i][j] = (int8_t)v; }
    for (int i = 0; i < m; i++)
        for (int j = 0; j < n; j++) { int v; f >> v; out.c[i][j] = v; }
    return true;
}

static bool run_case(Vtop* top, const Case& tc) {
    const int M = (int)tc.a.size();

    top->rst = 1; top->weight_load = 0; zero_sig(top->act_in_flat);
    zero_sig(top->weight_in_flat);
    tick(top);
    top->rst = 0;

    for (int r = 0; r < N; r++)
        for (int cc = 0; cc < N; cc++)
            put_byte(top->weight_in_flat, r * N + cc, (uint8_t)tc.w[r][cc]);
    zero_sig(top->act_in_flat);
    top->weight_load = 1;
    tick(top);
    top->weight_load = 0;
    zero_sig(top->weight_in_flat);

    const int total_ticks = M + 2 * N - 2;
    std::vector<std::vector<int32_t>> psum_hist(total_ticks, std::vector<int32_t>(N));

    for (int i = 0; i < total_ticks; i++) {
        for (int r = 0; r < N; r++) {
            int k = i - r;
            int8_t val = (k >= 0 && k < M) ? tc.a[k][r] : 0;
            put_byte(top->act_in_flat, r, (uint8_t)val);
        }
        tick(top);
        for (int cc = 0; cc < N; cc++) {
            uint32_t raw = 0;
            for (int b = 0; b < 4; b++) raw |= (uint32_t)get_byte(top->psum_out_flat, cc * 4 + b) << (b * 8);
            psum_hist[i][cc] = (int32_t)raw;
        }
    }

    bool pass = true;
    int fk = -1, fc = -1, fgot = 0, fexp = 0;
    for (int k = 0; k < M && pass; k++) {
        for (int cc = 0; cc < N; cc++) {
            int i = k + cc + N - 1;
            int32_t got = psum_hist[i][cc];
            int32_t exp = tc.c[k][cc];
            if (got != exp) { pass = false; fk = k; fc = cc; fgot = got; fexp = exp; break; }
        }
    }

    if (pass) printf("%-24s PASS (M=%d)\n", tc.name.c_str(), M);
    else printf("%-24s FAIL (M=%d) first mismatch k=%d c=%d got=%d exp=%d\n", tc.name.c_str(), M, fk, fc, fgot, fexp);
    return pass;
}

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    if (argc < 2) { fprintf(stderr, "usage: %s <vectors_dir>\n", argv[0]); return 1; }
    std::string dir = argv[1];

    std::ifstream manifest(dir + "/manifest.txt");
    if (!manifest) { fprintf(stderr, "cannot open %s/manifest.txt\n", dir.c_str()); return 1; }

    std::vector<std::string> files;
    std::string line;
    while (std::getline(manifest, line))
        if (!line.empty()) files.push_back(line);

    Vtop* top = new Vtop;
    bool all_pass = true;
    for (const auto& fn : files) {
        Case tc;
        tc.name = fn;
        if (!load_case(dir + "/" + fn, tc)) { all_pass = false; continue; }
        if (!run_case(top, tc)) all_pass = false;
    }
    delete top;

    printf(all_pass ? "ALL PASS\n" : "SOME FAILED\n");
    return all_pass ? 0 : 1;
}
