#include <cstdio>
#include <cstdint>
#include <cstring>
#include <vector>
#include "Vstream_axi_top.h"
#include "Vstream_axi_top_stream_axi_top.h"
#include "ram_types.h" // generated by the Makefile: defines RdRamT/WrRamT (see comment there)
#include "verilated.h"

#ifndef NN
#define NN 4
#endif

// word layouts (see stream_ctrl.sv header + axi4_dma_bridge.sv header):
//   read ram word  = NN int8 lanes, lane j at byte j   (DATA_W = NN*8),  byte addr = word*NN
//   write ram word = NN int32 lanes, lane c at word c  (DATA_W = NN*32), byte addr = word*NN*4
static const uint32_t W_BASE_WORD = 0;
static const uint32_t A_BASE_WORD = 512;

static void tick(Vstream_axi_top* top) {
    top->clk = 0; top->eval();
    top->clk = 1; top->eval();
}

template <typename T> static void put_bytes(T& dst, const uint8_t* src, size_t n) { memcpy(&dst, src, n); }
template <typename T> static void get_bytes(const T& src, uint8_t* dst, size_t n) { memcpy(dst, &src, n); }

static void load_row_i8(Vstream_axi_top* top, uint32_t base_word, int row, const int8_t* vals) {
    put_bytes(top->stream_axi_top->u_ram_rd->mem[base_word + row], reinterpret_cast<const uint8_t*>(vals), NN);
}
static void read_row_i32(Vstream_axi_top* top, uint32_t base_word, int row, int32_t* out) {
    get_bytes(top->stream_axi_top->u_ram_wr->mem[base_word + row], reinterpret_cast<uint8_t*>(out), NN * 4);
}

static void golden(const std::vector<std::vector<int8_t>>& a, const std::vector<std::vector<int8_t>>& w,
                    int m, std::vector<std::vector<int32_t>>& c) {
    c.assign(m, std::vector<int32_t>(NN, 0));
    for (int k = 0; k < m; k++)
        for (int col = 0; col < NN; col++) {
            int32_t acc = 0;
            for (int r = 0; r < NN; r++) acc += (int32_t)a[k][r] * (int32_t)w[r][col];
            c[k][col] = acc;
        }
}

static int run_one(Vstream_axi_top* top, const std::vector<std::vector<int8_t>>& a,
                    const std::vector<std::vector<int8_t>>& w, int m, uint32_t c_base_word,
                    uint32_t rd_mask, uint32_t wr_mask, uint32_t rd_seed, uint32_t wr_seed,
                    std::vector<std::vector<int32_t>>& got) {
    for (int i = 0; i < NN; i++) load_row_i8(top, W_BASE_WORD, i, w[i].data());
    for (int k = 0; k < m; k++) load_row_i8(top, A_BASE_WORD, k, a[k].data());

    top->rd_stall_mask = rd_mask; top->wr_stall_mask = wr_mask;
    top->rd_stall_seed = rd_seed; top->wr_stall_seed = wr_seed;
    top->start = 1;
    top->w_base = W_BASE_WORD * NN;
    top->a_base = A_BASE_WORD * NN;
    top->c_base = c_base_word * NN * 4;
    top->m_rows = m;
    tick(top);
    top->start = 0;

    int cycles = 0;
    int timeout = 200 * m + 4000;
    while (!top->done) {
        tick(top);
        cycles++;
        if (cycles > timeout) { printf("FAIL: timeout waiting for done (m=%d)\n", m); return -1; }
    }

    got.assign(m, std::vector<int32_t>(NN, 0));
    for (int k = 0; k < m; k++) read_row_i32(top, c_base_word, k, got[k].data());
    return cycles;
}

static uint32_t rng_state;
static int8_t rand_i8() { rng_state = rng_state * 1103515245u + 12345u; return (int8_t)(rng_state >> 24); }

static bool check(const std::vector<std::vector<int32_t>>& got, const std::vector<std::vector<int32_t>>& want,
                   int m, const char* tag) {
    for (int k = 0; k < m; k++)
        for (int c = 0; c < NN; c++)
            if (got[k][c] != want[k][c]) {
                printf("FAIL %s row=%d col=%d got=%d want=%d\n", tag, k, c, got[k][c], want[k][c]);
                return false;
            }
    return true;
}

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    Vstream_axi_top* top = new Vstream_axi_top;
    top->rst = 1; top->start = 0;
    top->rd_stall_mask = 0; top->wr_stall_mask = 0; top->rd_stall_seed = 0; top->wr_stall_seed = 0;
    tick(top); tick(top);
    top->rst = 0;
    tick(top);

    bool all_pass = true;
    int ms[] = {1, 4, 8, 32, 100};
    uint32_t seeds[] = {1, 2, 3, 4, 5};
    long total_cycles = 0, total_ops = 0;

    for (int mi = 0; mi < 5; mi++) {
        int m = ms[mi];
        for (int si = 0; si < 5; si++) {
            uint32_t seed = seeds[si];
            bool backpressure = (si % 2 == 1); // alternate clean / stalled runs across seeds
            rng_state = seed * 7919u + (uint32_t)m;
            std::vector<std::vector<int8_t>> a(m, std::vector<int8_t>(NN));
            std::vector<std::vector<int8_t>> w(NN, std::vector<int8_t>(NN));
            for (auto& row : a) for (auto& v : row) v = rand_i8();
            for (auto& row : w) for (auto& v : row) v = rand_i8();

            std::vector<std::vector<int32_t>> want;
            golden(a, w, m, want);

            uint32_t mask = backpressure ? 0xF : 0x0;
            uint32_t rseed = seed * 101u + 1, wseed = seed * 233u + 7;

            std::vector<std::vector<int32_t>> got;
            int cycles = run_one(top, a, w, m, /*c_base_word=*/0, mask, mask, rseed, wseed, got);
            if (cycles < 0) { all_pass = false; continue; }
            bool ok = check(got, want, m, "single-op");
            all_pass &= ok;
            total_cycles += cycles; total_ops++;
            if (ok) printf("PASS m=%d seed=%u backpressure=%d cycles=%d rd_beats=%u wr_beats=%u\n",
                            m, seed, backpressure, cycles,
                            top->stream_axi_top->rd_beat_count, top->stream_axi_top->wr_beat_count);
        }
    }

    // 3 back-to-back ops, different w/a/c bases each time, random backpressure on, no reset between
    {
        int m = 17;
        bool ok_all = true;
        for (int op = 0; op < 3; op++) {
            rng_state = 1000u + op;
            std::vector<std::vector<int8_t>> a(m, std::vector<int8_t>(NN));
            std::vector<std::vector<int8_t>> w(NN, std::vector<int8_t>(NN));
            for (auto& row : a) for (auto& v : row) v = rand_i8();
            for (auto& row : w) for (auto& v : row) v = rand_i8();
            std::vector<std::vector<int32_t>> want; golden(a, w, m, want);

            uint32_t c_base_word = 200u * (op + 1);
            uint32_t w_base_word_bytes_scale = W_BASE_WORD + 50u * op; // distinct w/a bases per op too
            top->rd_stall_mask = 0xF; top->wr_stall_mask = 0xF;
            top->rd_stall_seed = 55 + op; top->wr_stall_seed = 77 + op;

            // reuse run_one but with per-op w/a bases baked in via direct mem writes at shifted bases
            for (int i = 0; i < NN; i++) load_row_i8(top, w_base_word_bytes_scale, i, w[i].data());
            for (int k = 0; k < m; k++) load_row_i8(top, A_BASE_WORD + 50u * op, k, a[k].data());
            top->start = 1;
            top->w_base = w_base_word_bytes_scale * NN;
            top->a_base = (A_BASE_WORD + 50u * op) * NN;
            top->c_base = c_base_word * NN * 4;
            top->m_rows = m;
            tick(top);
            top->start = 0;
            int cycles = 0, timeout = 200 * m + 4000;
            while (!top->done) { tick(top); cycles++; if (cycles > timeout) { printf("FAIL: back-to-back op %d timeout\n", op); ok_all = false; break; } }
            if (cycles > timeout) continue;

            std::vector<std::vector<int32_t>> got(m, std::vector<int32_t>(NN, 0));
            for (int k = 0; k < m; k++) read_row_i32(top, c_base_word, k, got[k].data());
            char tag[32]; snprintf(tag, sizeof(tag), "b2b-op%d", op);
            bool ok = check(got, want, m, tag);
            ok_all &= ok;
            total_cycles += cycles; total_ops++;
            if (ok) printf("PASS back-to-back op=%d cycles=%d rd_beats=%u wr_beats=%u\n",
                            op, cycles, top->stream_axi_top->rd_beat_count, top->stream_axi_top->wr_beat_count);
        }
        all_pass &= ok_all;
    }

    printf("TOTAL: ops=%ld cycles=%ld avg_cycles/op=%.1f\n", total_ops, total_cycles,
           total_ops ? (double)total_cycles / total_ops : 0.0);

    delete top;
    if (all_pass) { printf("ALL PASS\n"); return 0; }
    return 1;
}
