#include <cstdio>
#include <cstdint>
#include <cstring>
#include <cstdlib>
#include <vector>
#include "Vstream_top.h"
#include "Vstream_top_stream_top.h"
#include "ram_types.h" // generated by the Makefile: defines WRamT/CRamT (see comment there)
#include "verilated.h"

#ifndef NN
#define NN 4
#endif

// word layouts (see stream_ctrl.sv header comment):
//   weight/act ram word = NN int8 lanes, lane j at byte j        (WIDTH = NN*8)
//   result ram word     = NN int32 lanes, lane c at word c       (WIDTH = NN*32)
static const int W_BASE = 0;
static const int A_BASE = 256;
static const int C_BASE = 4096;

static void tick(Vstream_top* top) {
    top->clk = 0; top->eval();
    top->clk = 1; top->eval();
}

// raw memcpy into a Verilated storage element (CData/SData/IData/QData/WData are all
// contiguous little-endian byte storage, so this works regardless of NN-dependent width).
template <typename T> static void put_bytes(T& dst, const uint8_t* src, size_t n) { memcpy(&dst, src, n); }
template <typename T> static void get_bytes(const T& src, uint8_t* dst, size_t n) { memcpy(dst, &src, n); }

static void load_row_i8(Vstream_top* top, int base, int row, const int8_t* vals) {
    put_bytes(top->stream_top->u_ram_aw->mem[base + row], reinterpret_cast<const uint8_t*>(vals), NN);
}

static void read_row_i32(Vstream_top* top, int base, int row, int32_t* out) {
    get_bytes(top->stream_top->u_ram_c->mem[base + row], reinterpret_cast<uint8_t*>(out), NN * 4);
}

// plain-C++ golden model: C[k][c] = sum_r A[k][r] * W[r][c], int32 accumulate
static void golden(const std::vector<std::vector<int8_t>>& a, const std::vector<std::vector<int8_t>>& w,
                    int m, std::vector<std::vector<int32_t>>& c) {
    c.assign(m, std::vector<int32_t>(NN, 0));
    for (int k = 0; k < m; k++)
        for (int col = 0; col < NN; col++) {
            int32_t acc = 0;
            for (int r = 0; r < NN; r++) acc += (int32_t)a[k][r] * (int32_t)w[r][col];
            c[k][col] = acc;
        }
}

// runs one matmul through the DUT, returns cycle count from start pulse to done pulse
static int run_one(Vstream_top* top, const std::vector<std::vector<int8_t>>& a,
                    const std::vector<std::vector<int8_t>>& w, int m,
                    std::vector<std::vector<int32_t>>& got) {
    for (int i = 0; i < NN; i++) load_row_i8(top, W_BASE, i, w[i].data());
    for (int k = 0; k < m; k++) load_row_i8(top, A_BASE, k, a[k].data());

    top->start = 1; top->w_base = W_BASE; top->a_base = A_BASE; top->c_base = C_BASE; top->m_rows = m;
    tick(top);
    top->start = 0;

    int cycles = 0;
    int timeout = 10 * m + 100;
    while (!top->done) {
        tick(top);
        cycles++;
        if (cycles > timeout) { printf("FAIL: timeout waiting for done (m=%d)\n", m); return -1; }
    }

    got.assign(m, std::vector<int32_t>(NN, 0));
    for (int k = 0; k < m; k++) read_row_i32(top, C_BASE, k, got[k].data());
    return cycles;
}

static uint32_t rng_state;
static int8_t rand_i8() { rng_state = rng_state * 1103515245u + 12345u; return (int8_t)(rng_state >> 24); }

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    Vstream_top* top = new Vstream_top;
    top->rst = 1; top->start = 0;
    tick(top); tick(top);
    top->rst = 0;
    tick(top);

    bool all_pass = true;
    int ms[] = {1, 4, 7, 64, 300};
    int seeds[] = {1, 2};
    // fill/drain/weight-load overhead: 2N (weight load, non-pipelined) + 1 (pulse) + 1 (prefetch)
    // + (2N-1) (systolic row/col skew) + 1 (done) <= 2N + NN*NN + 16 for all NN tested
    long budget_overhead = 2L * NN + (long)NN * NN + 16;

    for (int mi = 0; mi < 5; mi++) {
        for (int si = 0; si < 2; si++) {
            int m = ms[mi];
            rng_state = (uint32_t)(seeds[si] * 7919 + m);
            std::vector<std::vector<int8_t>> a(m, std::vector<int8_t>(NN));
            std::vector<std::vector<int8_t>> w(NN, std::vector<int8_t>(NN));
            for (auto& row : a) for (auto& v : row) v = rand_i8();
            for (auto& row : w) for (auto& v : row) v = rand_i8();

            std::vector<std::vector<int32_t>> got, want;
            golden(a, w, m, want);
            int cycles = run_one(top, a, w, m, got);
            if (cycles < 0) { all_pass = false; continue; }

            bool ok = true;
            for (int k = 0; k < m && ok; k++)
                for (int c = 0; c < NN && ok; c++)
                    if (got[k][c] != want[k][c]) {
                        printf("FAIL m=%d seed=%d row=%d col=%d got=%d want=%d\n",
                               m, seeds[si], k, c, got[k][c], want[k][c]);
                        ok = false;
                    }
            long budget = (long)m + budget_overhead;
            if (ok && cycles > budget) {
                printf("FAIL m=%d seed=%d cycles=%d exceeds budget=%ld\n", m, seeds[si], cycles, budget);
                ok = false;
            }
            if (ok) printf("PASS m=%d seed=%d cycles=%d (budget=%ld)\n", m, seeds[si], cycles, budget);
            all_pass &= ok;
        }
    }

    // back-to-back: two starts in a row with different weights, no reset between, proves reload works
    {
        int m = 5;
        rng_state = 42;
        std::vector<std::vector<int8_t>> a(m, std::vector<int8_t>(NN));
        std::vector<std::vector<int8_t>> w1(NN, std::vector<int8_t>(NN)), w2(NN, std::vector<int8_t>(NN));
        for (auto& row : a) for (auto& v : row) v = rand_i8();
        for (auto& row : w1) for (auto& v : row) v = rand_i8();
        for (auto& row : w2) for (auto& v : row) v = rand_i8();

        std::vector<std::vector<int32_t>> got1, want1, got2, want2;
        golden(a, w1, m, want1);
        run_one(top, a, w1, m, got1);
        golden(a, w2, m, want2);
        run_one(top, a, w2, m, got2);

        bool ok = true;
        for (int k = 0; k < m && ok; k++)
            for (int c = 0; c < NN && ok; c++) {
                if (got1[k][c] != want1[k][c]) { printf("FAIL back-to-back pass1 row=%d col=%d\n", k, c); ok = false; }
                if (got2[k][c] != want2[k][c]) { printf("FAIL back-to-back pass2 row=%d col=%d\n", k, c); ok = false; }
            }
        if (ok) printf("PASS back-to-back reload\n");
        all_pass &= ok;
    }

    delete top;
    if (all_pass) { printf("ALL PASS\n"); return 0; }
    return 1;
}
