// Full-stack driver test: sw/coproc_driver.h + sw/int8_mlp.h (portable C99, unmodified) drive
// the integrated coproc_axi_sim_top over Verilated MMIO + AXI DMA + IRQ, no Python in the loop.
// coproc_ops here is the ONLY sim-specific glue: dmem-port stores/loads for reg_write/reg_read,
// a backdoor into u_dut's u_ram_rd/u_ram_wr for mem_write/mem_read, and wait_irq ticks the clock
// until the irq line fires. Random AXI backpressure is enabled on every channel throughout.
#include <cstdio>
#include <cstdint>
#include <cstring>
#include <vector>
#include "Vcoproc_axi_sim_top.h"
#include "Vcoproc_axi_sim_top_coproc_axi_sim_top.h"
#include "ram_types.h" // generated by the Makefile: defines RdRamT/WrRamT
#include "verilated.h"

extern "C" {
#include "coproc_mmio.h"
#include "coproc_driver.h"
#include "int8_mlp.h"
}

#ifndef NN
#define NN 4
#endif

static Vcoproc_axi_sim_top *g_top;
static uint64_t g_cycles = 0;
static uint64_t g_mmio_ops = 0;
static uint64_t g_irqs_taken = 0;
static uint64_t g_commands_issued = 0; // host-side count; done_count in STATUS is only 16 bits and wraps

static void tick() {
    g_top->clk = 0; g_top->eval();
    g_top->clk = 1; g_top->eval();
    g_cycles++;
}

// ---------------- coproc_ops backing this TB ----------------
static void tb_reg_write(uint64_t addr, uint64_t val) {
    g_top->dmem_addr = addr; g_top->dmem_wdata = val; g_top->dmem_wen = 1; g_top->dmem_funct3 = 0b011; // SD
    tick();
    g_top->dmem_wen = 0;
    g_mmio_ops++;
    if (addr == COPROC_REG_CMD && val == 1) g_commands_issued++;
}
static uint64_t tb_reg_read(uint64_t addr) {
    g_top->dmem_addr = addr; g_top->dmem_wen = 0; g_top->dmem_funct3 = 0b011; // LD
    g_top->eval();
    uint64_t v = g_top->dmem_rdata;
    tick();
    g_mmio_ops++;
    return v;
}

// word layouts (see stream_ctrl.sv / axi4_dma_bridge.sv): read ram word = NN int8 lanes,
// byte addr = word*NN; write ram word = NN int32 lanes, byte addr = word*NN*4
static void tb_mem_write(uint64_t byte_addr, const void *src, uint64_t n) {
    // src is either a packed weight/act tile (int8 bytes going into u_ram_rd) -- byte-addressed
    // directly into the read RAM's byte-flat storage via its word array.
    auto &ram = g_top->coproc_axi_sim_top->u_ram_rd->mem;
    const uint8_t *s = (const uint8_t *)src;
    for (uint64_t i = 0; i < n; i++) {
        uint64_t addr = byte_addr + i;
        uint64_t word = addr / NN, lane = addr % NN;
        reinterpret_cast<uint8_t *>(&ram[word])[lane] = s[i];
    }
}
static void tb_mem_read(uint64_t byte_addr, void *dst, uint64_t n) {
    auto &ram = g_top->coproc_axi_sim_top->u_ram_wr->mem;
    uint8_t *d = (uint8_t *)dst;
    for (uint64_t i = 0; i < n; i++) {
        uint64_t addr = byte_addr + i;
        uint64_t word = addr / (NN * 4), lane = addr % (NN * 4);
        d[i] = reinterpret_cast<uint8_t *>(&ram[word])[lane];
    }
}
static void tb_wait_irq() {
    int guard = 0;
    while (!g_top->irq) {
        tick();
        if (++guard > 100000) { fprintf(stderr, "FATAL: wait_irq timeout\n"); exit(1); }
    }
    g_irqs_taken++;
}

static const coproc_ops TB_OPS = { tb_reg_write, tb_reg_read, tb_mem_write, tb_mem_read, tb_wait_irq };

int main(int argc, char **argv) {
    Verilated::commandArgs(argc, argv);
    g_top = new Vcoproc_axi_sim_top;
    g_top->rst = 1; g_top->dmem_wen = 0; g_top->dmem_addr = 0; g_top->dmem_wdata = 0; g_top->dmem_funct3 = 0;
    g_top->rd_stall_mask = 0xF; g_top->wr_stall_mask = 0xF;
    g_top->rd_stall_seed = 0xC0FFEE; g_top->wr_stall_seed = 0xFEEDBEEF;
    tick(); tick();
    g_top->rst = 0;
    tick();

    // load static vectors produced by gen_vectors.py
    FILE *fw = fopen("vectors/weights.bin", "rb");
    FILE *fi = fopen("vectors/images.bin", "rb");
    FILE *fl = fopen("vectors/labels.bin", "rb");
    FILE *fe = fopen("vectors/expected_logits.bin", "rb");
    if (!fw || !fi || !fl || !fe) { fprintf(stderr, "FATAL: run gen_vectors.py first\n"); return 1; }

    static int8_t W1[MLP_IN * MLP_HIDDEN];
    static int32_t b1[MLP_HIDDEN];
    static int8_t W2[MLP_HIDDEN * MLP_OUT];
    static int32_t b2[MLP_OUT];
    (void)fread(W1, 1, sizeof(W1), fw);
    (void)fread(b1, 4, MLP_HIDDEN, fw);
    (void)fread(W2, 1, sizeof(W2), fw);
    (void)fread(b2, 4, MLP_OUT, fw);
    fclose(fw);

    char manifest[256] = {0};
    FILE *fm = fopen("vectors/manifest.txt", "r");
    int n_images = 32, M0_1 = 0, shift_1 = 0;
    if (fm) {
        while (fgets(manifest, sizeof(manifest), fm)) {
            sscanf(manifest, "n_images=%d", &n_images);
            sscanf(manifest, "M0_1=%d shift_1=%d", &M0_1, &shift_1);
        }
        fclose(fm);
    }

    std::vector<int8_t> images(n_images * MLP_IN);
    std::vector<int32_t> labels(n_images);
    std::vector<int32_t> expected(n_images * MLP_OUT);
    (void)fread(images.data(), 1, images.size(), fi);
    (void)fread(labels.data(), 4, n_images, fl);
    (void)fread(expected.data(), 4, n_images * MLP_OUT, fe);
    fclose(fi); fclose(fl); fclose(fe);

    int8_mlp_weights wt;
    wt.W1_i8 = W1; wt.b1_i32 = b1; wt.W2_i8 = W2; wt.b2_i32 = b2;
    wt.M0_1 = M0_1; wt.shift_1 = shift_1;

    // scratch layout in the shared read/write RAMs: 4 queue slots, each sized for the largest
    // possible tile (MAX_ROWS rows), all well inside RD_DEPTH/WR_DEPTH=65536 words.
    coproc_buffers bufs;
    const uint64_t W_SLOT_BYTES = COPROC_TILE * COPROC_TILE;                 // 16B
    const uint64_t A_SLOT_BYTES = (uint64_t)COPROC_MAX_ROWS * COPROC_TILE;   // 4096B
    const uint64_t C_SLOT_BYTES = (uint64_t)COPROC_MAX_ROWS * COPROC_TILE * 4; // 16384B
    for (int s = 0; s < COPROC_QDEPTH; s++) {
        bufs.w_base[s] = (uint64_t)s * A_SLOT_BYTES;                 // read-RAM region A
        bufs.a_base[s] = 4 * A_SLOT_BYTES + (uint64_t)s * A_SLOT_BYTES; // read-RAM region B
        bufs.c_base[s] = (uint64_t)s * C_SLOT_BYTES;                 // write-RAM
    }
    (void)W_SLOT_BYTES;

    int correct = 0;
    bool all_bitexact = true;
    for (int im = 0; im < n_images; im++) {
        int32_t logits[MLP_OUT];
        int8_mlp_infer(&TB_OPS, &wt, &images[im * MLP_IN], logits, &bufs);

        bool bitexact = true;
        for (int c = 0; c < MLP_OUT; c++)
            if (logits[c] != expected[im * MLP_OUT + c]) bitexact = false;
        all_bitexact &= bitexact;

        int pred = int8_mlp_argmax(logits);
        int pred_exp = int8_mlp_argmax(&expected[im * MLP_OUT]);
        if (pred == labels[im]) correct++;
        printf("%s image=%2d pred=%d expected_pred=%d label=%d bitexact=%s\n",
               bitexact ? "PASS" : "FAIL", im, pred, pred_exp, labels[im], bitexact ? "yes" : "no");
    }

    uint32_t rd_beats = g_top->coproc_axi_sim_top->rd_beat_count;
    uint32_t wr_beats = g_top->coproc_axi_sim_top->wr_beat_count;
    uint64_t status = tb_reg_read(COPROC_REG_STATUS);
    uint32_t done_count = (uint32_t)((status >> COPROC_STATUS_DONE_COUNT_SHIFT) & COPROC_STATUS_DONE_COUNT_MASK);

    printf("\n%d/%d images bit-exact vs expected_logits.bin\n", all_bitexact ? n_images : correct, n_images);
    printf("accuracy on this batch (predicted==label): %d/%d\n", correct, n_images);
    printf("total MMIO ops=%llu, IRQs taken=%llu, commands issued=%llu (HW done_count, 16b wrapped=%u)\n",
           (unsigned long long)g_mmio_ops, (unsigned long long)g_irqs_taken,
           (unsigned long long)g_commands_issued, done_count);
    printf("total AXI beats: rd=%u wr=%u\n", rd_beats, wr_beats);
    printf("total cycles=%llu\n", (unsigned long long)g_cycles);

    bool irq_count_ok = (g_irqs_taken == g_commands_issued);
    printf("%s IRQs taken == commands issued\n", irq_count_ok ? "PASS" : "FAIL");

    bool all_pass = all_bitexact && irq_count_ok;
    delete g_top;
    if (all_pass) { printf("ALL PASS\n"); return 0; }
    return 1;
}
