#include <cstdio>
#include <cstdint>
#include <cstring>
#include <vector>
#include "Vcoproc_mmio_top.h"
#include "Vcoproc_mmio_top_coproc_mmio_top.h"
#include "ram_types.h" // generated by the Makefile: defines StreamT/WRamT/CRamT (see comment there)
#include "verilated.h"

#ifndef NN
#define NN 4
#endif

// register offsets, mirrors sw/coproc_mmio.h
static const uint64_t BASE     = 0x1000'0000ULL;
static const uint64_t REG_W    = BASE + 0x00;
static const uint64_t REG_A    = BASE + 0x08;
static const uint64_t REG_C    = BASE + 0x10;
static const uint64_t REG_M    = BASE + 0x18;
static const uint64_t REG_CMD  = BASE + 0x20;
static const uint64_t REG_STAT = BASE + 0x28;
static const uint64_t REG_IRQ  = BASE + 0x30;
static const uint64_t REG_ID   = BASE + 0x38;

static void tick(Vcoproc_mmio_top* top) {
    top->clk = 0; top->eval();
    top->clk = 1; top->eval();
}

// drives the dmem port exactly as a core store instruction would: addr/wdata/funct3 with
// wen high for one cycle
static void mmio_write64(Vcoproc_mmio_top* top, uint64_t addr, uint64_t val) {
    top->dmem_addr = addr; top->dmem_wdata = val; top->dmem_wen = 1; top->dmem_funct3 = 0b011; // SD
    tick(top);
    top->dmem_wen = 0;
}

// drives addr/funct3 as a load would; the register block returns rdata combinationally
static uint64_t mmio_read64(Vcoproc_mmio_top* top, uint64_t addr) {
    top->dmem_addr = addr; top->dmem_wen = 0; top->dmem_funct3 = 0b011; // LD
    top->eval();
    uint64_t v = top->dmem_rdata;
    tick(top);
    return v;
}

static void mmio_enqueue(Vcoproc_mmio_top* top, uint64_t w, uint64_t a, uint64_t c, uint64_t m) {
    mmio_write64(top, REG_W, w);
    mmio_write64(top, REG_A, a);
    mmio_write64(top, REG_C, c);
    mmio_write64(top, REG_M, m);
    mmio_write64(top, REG_CMD, 1);
}

// word layouts match stream_ctrl.sv: weight/act ram word = NN int8 lanes, result ram = NN int32
template <typename T> static void put_bytes(T& dst, const uint8_t* src, size_t n) { memcpy(&dst, src, n); }
template <typename T> static void get_bytes(const T& src, uint8_t* dst, size_t n) { memcpy(dst, &src, n); }

static void load_row_i8(Vcoproc_mmio_top* top, int base, int row, const int8_t* vals) {
    put_bytes(top->coproc_mmio_top->u_stream->u_ram_aw->mem[base + row], reinterpret_cast<const uint8_t*>(vals), NN);
}
static void read_row_i32(Vcoproc_mmio_top* top, int base, int row, int32_t* out) {
    get_bytes(top->coproc_mmio_top->u_stream->u_ram_c->mem[base + row], reinterpret_cast<uint8_t*>(out), NN * 4);
}

static void golden(const std::vector<std::vector<int8_t>>& a, const std::vector<std::vector<int8_t>>& w,
                    int m, std::vector<std::vector<int32_t>>& c) {
    c.assign(m, std::vector<int32_t>(NN, 0));
    for (int k = 0; k < m; k++)
        for (int col = 0; col < NN; col++) {
            int32_t acc = 0;
            for (int r = 0; r < NN; r++) acc += (int32_t)a[k][r] * (int32_t)w[r][col];
            c[k][col] = acc;
        }
}

static uint32_t rng_state;
static int8_t rand_i8() { rng_state = rng_state * 1103515245u + 12345u; return (int8_t)(rng_state >> 24); }

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    Vcoproc_mmio_top* top = new Vcoproc_mmio_top;
    top->rst = 1; top->dmem_wen = 0; top->dmem_addr = 0; top->dmem_wdata = 0; top->dmem_funct3 = 0;
    tick(top); tick(top);
    top->rst = 0;
    tick(top);

    bool all_pass = true;

    // --- ID register ---
    {
        uint64_t id = mmio_read64(top, REG_ID);
        uint64_t want = 0x7E4A5A00ULL | NN;
        bool ok = (id == want);
        printf("%s ID register got=0x%llx want=0x%llx\n", ok ? "PASS" : "FAIL",
               (unsigned long long)id, (unsigned long long)want);
        all_pass &= ok;
    }

    // --- enqueue 4 commands back-to-back before the first finishes, proving the FIFO ---
    {
        const int NCMD = 4;
        int ms[NCMD] = {3, 5, 2, 6};
        int w_bases[NCMD] = {0, 64, 128, 192};
        int a_bases[NCMD] = {1024, 1280, 1536, 1792};
        int c_bases[NCMD] = {8192, 8320, 8448, 8576};
        std::vector<std::vector<std::vector<int8_t>>> a_all(NCMD), w_all(NCMD);
        std::vector<std::vector<std::vector<int32_t>>> want_all(NCMD);
        rng_state = 1;

        for (int i = 0; i < NCMD; i++) {
            int m = ms[i];
            a_all[i].assign(m, std::vector<int8_t>(NN));
            w_all[i].assign(NN, std::vector<int8_t>(NN));
            for (auto& row : a_all[i]) for (auto& v : row) v = rand_i8();
            for (auto& row : w_all[i]) for (auto& v : row) v = rand_i8();
            for (int r = 0; r < NN; r++) load_row_i8(top, w_bases[i], r, w_all[i][r].data());
            for (int k = 0; k < m; k++) load_row_i8(top, a_bases[i], k, a_all[i][k].data());
            golden(a_all[i], w_all[i], m, want_all[i]);
        }

        // enqueue all 4 immediately, back-to-back, before the first can possibly finish
        for (int i = 0; i < NCMD; i++)
            mmio_enqueue(top, w_bases[i], a_bases[i], c_bases[i], ms[i]);

        uint64_t status = mmio_read64(top, REG_STAT);
        printf("INFO status right after enqueueing 4: 0x%llx (queue should not be empty)\n", (unsigned long long)status);

        // poll until queue drains and datapath goes idle
        int timeout = 5000, cycles = 0;
        do {
            status = mmio_read64(top, REG_STAT);
            cycles++;
        } while ((!(status & 0x4) || (status & 0x1)) && cycles < timeout);

        bool drained = (status & 0x4) && !(status & 0x1);
        printf("%s all 4 commands drained after %d poll cycles, status=0x%llx\n",
               drained ? "PASS" : "FAIL", cycles, (unsigned long long)status);
        all_pass &= drained;

        int done_count = (status >> 16) & 0xFFFF;
        bool dc_ok = (done_count == NCMD);
        printf("%s done_count=%d want=%d\n", dc_ok ? "PASS" : "FAIL", done_count, NCMD);
        all_pass &= dc_ok;

        for (int i = 0; i < NCMD; i++) {
            std::vector<std::vector<int32_t>> got(ms[i], std::vector<int32_t>(NN));
            for (int k = 0; k < ms[i]; k++) read_row_i32(top, c_bases[i], k, got[k].data());
            bool ok = true;
            for (int k = 0; k < ms[i] && ok; k++)
                for (int c = 0; c < NN && ok; c++)
                    if (got[k][c] != want_all[i][k][c]) {
                        printf("FAIL cmd=%d row=%d col=%d got=%d want=%d\n", i, k, c, got[k][c], want_all[i][k][c]);
                        ok = false;
                    }
            if (ok) printf("PASS cmd=%d (m=%d) result matches golden\n", i, ms[i]);
            all_pass &= ok;
        }
    }

    // --- queue_full: enqueue 5 while the datapath is stalled, 5th must be dropped ---
    {
        // hold the datapath busy with a long matmul so the FIFO can back up
        int m = 500;
        std::vector<std::vector<int8_t>> a(m, std::vector<int8_t>(NN));
        std::vector<std::vector<int8_t>> w(NN, std::vector<int8_t>(NN));
        rng_state = 99;
        for (auto& row : a) for (auto& v : row) v = rand_i8();
        for (auto& row : w) for (auto& v : row) v = rand_i8();
        for (int r = 0; r < NN; r++) load_row_i8(top, 0, r, w[r].data());
        for (int k = 0; k < m; k++) load_row_i8(top, 1024, k, a[k].data());

        mmio_enqueue(top, 0, 1024, 8192, m); // consumed immediately, occupies the datapath
        for (int i = 0; i < 4; i++) mmio_enqueue(top, 0, 1024, 8192, 1); // fills the 4-deep FIFO

        uint64_t status = mmio_read64(top, REG_STAT);
        bool full_ok = (status & 0x2) != 0;
        printf("%s queue_full asserted with datapath busy + 4 queued, status=0x%llx\n", full_ok ? "PASS" : "FAIL",
               (unsigned long long)status);
        all_pass &= full_ok;

        uint64_t dc_before = (status >> 16) & 0xFFFF;
        mmio_enqueue(top, 0, 1024, 8192, 1); // 5th: must be dropped, no change in queue depth

        status = mmio_read64(top, REG_STAT);
        bool still_full = (status & 0x2) != 0;
        printf("%s queue_full still 1 after attempted 5th enqueue, status=0x%llx\n", still_full ? "PASS" : "FAIL",
               (unsigned long long)status);
        all_pass &= still_full;

        // drain everything out before moving on
        int timeout = 5000, cycles = 0;
        do { status = mmio_read64(top, REG_STAT); cycles++; }
        while ((!(status & 0x4) || (status & 0x1)) && cycles < timeout);
        bool drained = (status & 0x4) && !(status & 0x1);
        printf("%s drained after full/drop test, status=0x%llx\n", drained ? "PASS" : "FAIL", (unsigned long long)status);
        all_pass &= drained;

        uint64_t dc_after = (status >> 16) & 0xFFFF;
        bool dc_ok = (dc_after - dc_before) == 5; // the busy long matmul + 4 accepted queued ones
        printf("%s done_count advanced by %llu (want 5, confirms the dropped 5th never ran)\n",
               dc_ok ? "PASS" : "FAIL", (unsigned long long)(dc_after - dc_before));
        all_pass &= dc_ok;
    }

    // --- IRQ assertion and RW1C clear ---
    {
        mmio_write64(top, REG_IRQ, 0x3); // enable + clear any pending latched by earlier tests' done pulses
        uint64_t irq_before = mmio_read64(top, REG_IRQ);
        printf("INFO irq reg after enabling: 0x%llx\n", (unsigned long long)irq_before);

        std::vector<std::vector<int8_t>> a(2, std::vector<int8_t>(NN, 1));
        std::vector<std::vector<int8_t>> w(NN, std::vector<int8_t>(NN, 1));
        for (int r = 0; r < NN; r++) load_row_i8(top, 0, r, w[r].data());
        for (int k = 0; k < 2; k++) load_row_i8(top, 1024, k, a[k].data());
        mmio_enqueue(top, 0, 1024, 8192, 2);

        int timeout = 500, cycles = 0;
        while (!top->irq && cycles < timeout) { tick(top); cycles++; }
        bool irq_ok = (top->irq != 0);
        printf("%s irq asserted after done (waited %d cycles)\n", irq_ok ? "PASS" : "FAIL", cycles);
        all_pass &= irq_ok;

        uint64_t irq_reg = mmio_read64(top, REG_IRQ);
        bool pending_ok = (irq_reg & 0x2) != 0;
        printf("%s IRQ_PENDING readable as set, irq reg=0x%llx\n", pending_ok ? "PASS" : "FAIL",
               (unsigned long long)irq_reg);
        all_pass &= pending_ok;

        mmio_write64(top, REG_IRQ, 0x3); // RW1C: keep enabled, clear pending
        tick(top);
        bool irq_cleared = (top->irq == 0);
        printf("%s irq deasserted after RW1C clear\n", irq_cleared ? "PASS" : "FAIL");
        all_pass &= irq_cleared;

        uint64_t irq_reg2 = mmio_read64(top, REG_IRQ);
        bool pending_cleared = (irq_reg2 & 0x2) == 0;
        printf("%s IRQ_PENDING readable as cleared, irq reg=0x%llx\n", pending_cleared ? "PASS" : "FAIL",
               (unsigned long long)irq_reg2);
        all_pass &= pending_cleared;
    }

    delete top;
    if (all_pass) { printf("ALL PASS\n"); return 0; }
    return 1;
}
